import type { ExpoConfig } from 'expo/config';

/** The Play package name can never change after the first upload; Google sign-in is tied to it too. */
const ANDROID_PACKAGE = 'com.codeville.calico';

const config: ExpoConfig = {
  name: 'Calico',
  slug: 'calico',
  scheme: 'calico',
  version: '1.0.0',
  orientation: 'portrait',
  userInterfaceStyle: 'automatic',
  icon: './assets/images/icon.png',
  android: {
    package: ANDROID_PACKAGE,
    // Generated by `npm run brand` (scripts/brand.mjs) from design/v2's painted icon on forest green.
    adaptiveIcon: {
      foregroundImage: './assets/images/adaptive-icon.png',
      monochromeImage: './assets/images/android-icon-monochrome.png',
      backgroundColor: '#1F3A32',
    },
    permissions: ['CAMERA', 'POST_NOTIFICATIONS', 'VIBRATE'],
    blockedPermissions: ['android.permission.RECORD_AUDIO'],
  },
  plugins: [
    'expo-router',
    'expo-font',
    [
      'expo-camera',
      {
        cameraPermission: 'Calico uses the camera to scan barcodes and photograph book covers.',
        recordAudioAndroid: false,
      },
    ],
    ['expo-image-picker', { photosPermission: 'Calico lets you pick a book cover photo from your gallery.' }],
    ['expo-notifications', { icon: './assets/images/notification-icon.png', color: '#EC6426' }],
    // Kiri on the splash gradient's midpoint; AnimatedSplash takes over from this frame (app/_layout.tsx).
    ['expo-splash-screen', { backgroundColor: '#203830', image: './assets/images/splash.png', imageWidth: 148 }],
    '@react-native-google-signin/google-signin',
    // Source maps upload during EAS builds when SENTRY_ORG, SENTRY_PROJECT and SENTRY_AUTH_TOKEN are set.
    '@sentry/react-native/expo',
  ],
  experiments: { typedRoutes: true },
  extra: { eas: { projectId: '139d5856-a401-4de1-bc3d-334305a0ad50' } },
  // EAS Update: JS-only fixes ship with `eas update --channel <profile>`. Bump `version` whenever native
  // code changes (new native package, config plugin, SDK upgrade) so old builds never get an incompatible update.
  runtimeVersion: { policy: 'appVersion' },
  updates: { url: 'https://u.expo.dev/139d5856-a401-4de1-bc3d-334305a0ad50' },
};

export default config;
