// Generated by `npm run illustrations` (scripts/illustrations.py). Do not edit.

export const illustrations = {
  bookshelf: { source: require('../../../assets/illustrations/bookshelf.webp'), width: 520, height: 893 },
  'cat-loaf': { source: require('../../../assets/illustrations/cat-loaf.webp'), width: 600, height: 489 },
  'cat-magnifier': { source: require('../../../assets/illustrations/cat-magnifier.webp'), width: 516, height: 577 },
  'cat-scatter': { source: require('../../../assets/illustrations/cat-scatter.webp'), width: 520, height: 438 },
  'cat-shelf-sleep': { source: require('../../../assets/illustrations/cat-shelf-sleep.webp'), width: 680, height: 340 },
  'cat-stretch': { source: require('../../../assets/illustrations/cat-stretch.webp'), width: 620, height: 538 },
  'cover-atlas': { source: require('../../../assets/illustrations/cover-atlas.webp'), width: 288, height: 432 },
  'cover-brighter': { source: require('../../../assets/illustrations/cover-brighter.webp'), width: 288, height: 432 },
  'cover-midnight': { source: require('../../../assets/illustrations/cover-midnight.webp'), width: 312, height: 468 },
  'desk-scene': { source: require('../../../assets/illustrations/desk-scene.webp'), width: 620, height: 930 },
  'girl-reading': { source: require('../../../assets/illustrations/girl-reading.webp'), width: 516, height: 1193 },
  'open-book-world': { source: require('../../../assets/illustrations/open-book-world.webp'), width: 560, height: 463 },
  'stack-books': { source: require('../../../assets/illustrations/stack-books.webp'), width: 360, height: 448 },
  asterisk: { source: require('../../../assets/illustrations/asterisk.webp'), width: 90, height: 90 },
  bookmark: { source: require('../../../assets/illustrations/bookmark.webp'), width: 78, height: 79 },
  dots: { source: require('../../../assets/illustrations/dots.webp'), width: 132, height: 132 },
  flower: { source: require('../../../assets/illustrations/flower.webp'), width: 102, height: 101 },
  heart: { source: require('../../../assets/illustrations/heart.webp'), width: 102, height: 110 },
  moon: { source: require('../../../assets/illustrations/moon.webp'), width: 162, height: 162 },
  mug: { source: require('../../../assets/illustrations/mug.webp'), width: 90, height: 121 },
  openbook: { source: require('../../../assets/illustrations/openbook.webp'), width: 114, height: 114 },
  sprout: { source: require('../../../assets/illustrations/sprout.webp'), width: 90, height: 96 },
  stack: { source: require('../../../assets/illustrations/stack.webp'), width: 170, height: 172 },
  star: { source: require('../../../assets/illustrations/star.webp'), width: 42, height: 42 },
  strokes: { source: require('../../../assets/illustrations/strokes.webp'), width: 138, height: 124 },
  sun: { source: require('../../../assets/illustrations/sun.webp'), width: 170, height: 169 },
  wave: { source: require('../../../assets/illustrations/wave.webp'), width: 126, height: 127 },
  'app-icon': { source: require('../../../assets/illustrations/app-icon.webp'), width: 162, height: 162 },
} as const;

export type IllustrationName = keyof typeof illustrations;
