"""Compresses the design/v2 illustrations for the app and writes their lookup table.

Usage: npm run illustrations   (needs Pillow with WebP support)

- Reads design/v2/assets/{art,el}/*.png (the Claude Design export).
- Writes assets/illustrations/<name>.webp, each scaled to at most 3x the widest it's shown in the
  prototype (sharp on xxhdpi phones), lossy WebP with alpha.
- Writes src/components/calico/illustrations.generated.ts: name -> require() + intrinsic size.
"""
import re
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'design/v2/assets'
OUT = ROOT / 'assets/illustrations'
TS = ROOT / 'src/components/calico/illustrations.generated.ts'
PROTOTYPE = ROOT / 'design/v2/Calico Prototype.dc.html'
DENSITY = 3
QUALITY = 86
# Widest planned use outside the prototype (feature graphic, splash), in dp.
EXTRA = {'cat-loaf': 240, 'app-icon': 54}


def display_widths() -> dict[str, int]:
    html = PROTOTYPE.read_text()
    widths: dict[str, int] = {}
    for name, width in re.findall(r'assets/(?:art|el)/([a-z0-9-]+)\.png"[^>]*?width:(\d+)px', html):
        widths[name] = max(widths.get(name, 0), int(width))
    for name, width in EXTRA.items():
        widths[name] = max(widths.get(name, 0), width)
    return widths


def paper_tiles() -> None:
    """The prototype's paper fleck: a 0.5dp dot every 4dp (`--fleck`). Saved @3x so React Native tiles it
    every 4dp. Day: ink at 4%; night: cream at 5%."""
    size, ss = 12, 8  # 4dp at 3x, drawn 8x supersampled
    for name, rgba in [('paper-day', (28, 23, 20, 10)), ('paper-night', (230, 240, 233, 13))]:
        big = Image.new('RGBA', (size * ss, size * ss), (0, 0, 0, 0))
        r = 1.5 * ss  # 0.5dp at 3x
        c = size * ss / 2
        ImageDraw.Draw(big).ellipse((c - r, c - r, c + r, c + r), fill=rgba)
        big.resize((size, size), Image.LANCZOS).save(OUT / f'{name}@3x.png')
        print(f'{name}@3x.png  {size}x{size}')


def main() -> None:
    widths = display_widths()
    OUT.mkdir(parents=True, exist_ok=True)
    entries = []
    before = after = 0
    # The painted app icon is shown in the app too (Welcome, Settings → About).
    sources = sorted([*SRC.glob('art/*.png'), *SRC.glob('el/*.png')]) + [SRC / 'app-icon-192.png']
    for path in sources:
        name = 'app-icon' if path.stem == 'app-icon-192' else path.stem
        im = Image.open(path).convert('RGBA')
        cap = widths.get(name, 120) * DENSITY
        if im.width > cap:
            im = im.resize((cap, round(im.height * cap / im.width)), Image.LANCZOS)
        out = OUT / f'{name}.webp'
        im.save(out, 'WEBP', quality=QUALITY, method=6)
        before += path.stat().st_size
        after += out.stat().st_size
        entries.append((name, im.width, im.height))
        print(f'{name:18} {im.width:4}x{im.height:<4} {out.stat().st_size // 1024:4} KB')

    paper_tiles()

    lines = [
        '// Generated by `npm run illustrations` (scripts/illustrations.py). Do not edit.',
        '',
        'export const illustrations = {',
    ]
    for name, w, h in entries:
        lines.append(f"  '{name}': {{ source: require('../../../assets/illustrations/{name}.webp'), width: {w}, height: {h} }},")
    lines += ['} as const;', '', 'export type IllustrationName = keyof typeof illustrations;', '']
    TS.write_text('\n'.join(lines))
    print(f'{len(entries)} files: {before // 1024} KB -> {after // 1024} KB')


if __name__ == '__main__':
    main()
